In [6]:
import numpy as np

array = np.array([[1,2,3,4], [5,6,7,8]])

print(array.shape)

print(array[0, 2])

print(array[0,:])

print(array[:,1])

(2, 4)
3
[1 2 3 4]
[2 6]


In [7]:
import numpy as np
PI_true = "3.141592653589793238462643"

for prec in (np.float16, np.float32, np.float64):
    pi = 4*np.arctan(1, dtype=prec)
    print("{} - {:.24f}".format(str(prec), pi))


print("True value", " "*12, "-", PI_true)


<class 'numpy.float16'> - 3.140625000000000000000000
<class 'numpy.float32'> - 3.141592741012573242187500
<class 'numpy.float64'> - 3.141592653589793115997963
True value              - 3.141592653589793238462643


In [1]:
import numpy as np

array = np.arange(24)               # Create 1D array of integers 0-23

# Every element up to the 4th index (non-inclusive)
print( array[:3] )                  # [0 1 2]
# Every 6th element
print( array[::6] )                 # [0 6 12 18]
# Count backwards from 5th element
print( array[5::-1] )               # [5 4 3 2 1 0]

array = np.reshape(array, (4,6))    # Reshape 1D array into a 4x6 2D array

# Get the first element in axis 0 and flip
print( array[0, ::-1] )             # [5 4 3 2 1 0]
# Return the first 3 elements of the 3rd element in axis 1
print( array[:3, 2] )               # [2 8 14]


[0 1 2]
[ 0  6 12 18]
[5 4 3 2 1 0]
[5 4 3 2 1 0]
[ 2  8 14]


In [10]:
import numpy as np

array = np.arange(24)                   # Create 1D array of integers 0-23
array = np.reshape(array, (4,6))        # Reshape 1D array into a 4x6 2D array


# Get the 1st and 4nd elements along the first axis
print(array[np.array([0, 3])])          #[[ 0  1  2  3  4  5]
                                        # [18 19 20 21 22 23]]

# Get the 1st, 2rd and 5th elements along the second axis for 
# all elements in the first axis 
print(array[:, np.array([0, 1, 4])])    #[[ 0  1  4]
                                        # [ 6  7 10]
                                        # [12 13 16]
                                        # [18 19 22]]

# Get ll items in the array that are greater than 17
print(array[array > 17])                # [18 19 20 21 22 23]

[[ 0  1  2  3  4  5]
 [18 19 20 21 22 23]]
[[ 0  1  4]
 [ 6  7 10]
 [12 13 16]
 [18 19 22]]
[18 19 20 21 22 23]


In [1]:
import numpy as np

# Create two 2x2 matrix arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Print intermediate step for matrix multiplication
I = np.einsum("ij,jk->ijk", A, B)
print(I)

# Print result of matrix multiplication using einsum
C = np.einsum("ij,jk->ik", A, B)
print(C)

[[[ 5  6]
  [14 16]]

 [[15 18]
  [28 32]]]
[[19 22]
 [43 50]]
